name: Just Postman Tests

on:
  workflow_dispatch:

jobs:
  postman:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Start API server
        run: |
          $env:ASPNETCORE_URLS = "http://localhost:3000"
          dotnet run --project crm-site/server/server.csproj &
          $serverReady = $false
          $maxAttempts = 20
          for ($i = 0; $i -lt $maxAttempts; $i++) {
            Write-Host "Waiting for server... ($i)"
            try {
              $response = Invoke-WebRequest -Uri "http://localhost:3000/api/login" -UseBasicParsing
              if ($response.StatusCode -eq 200) {
                Write-Host "✅ Server is up!"
                break
              }
            } catch {
              Start-Sleep -Seconds 3
            }
            if ($i -eq $maxAttempts - 1) {
              throw "❌ Server did not start in time."
            }
          }

        shell: pwsh

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman tests
        run: newman run crm-site/postman_test/linustest.postman_collection.json
